import { DocumentFile, VocabularyItem, Folder, Deck } from '../types';

export const SAMPLE_DOCUMENTS: DocumentFile[] = [
  {
    id: 'doc-1',
    name: "Read People Like a Book",
    title: "Read People Like a Book",
    author: "Patrick King",
    size: 2450000,
    uploadedAt: Date.now() - 86400000 * 3,
    lastReadAt: Date.now() - 3600000 * 2,
    currentPage: 34,
    totalPages: 240,
    language: "English",
    fileType: 'sample',
    coverColor: 'color-1856B7',
    category: 'Best choice',
    favorite: true,
    planToRead: false,
    completed: false,
    rating: 4.9,
    contentData: `# Chapter 1: How to Analyze People\n\nSpeed-reading people, deciphering body language, detecting lies, and understanding human psychology.\n\nObserving body language is akin to learning a second silent language. When you know what to look for, every micro-expression, posture shift, and voice tone reveals a wealth of unsaid feelings.`
  },
  {
    id: 'doc-2',
    name: "The Power of Your Subconscious Mind",
    title: "The Power of Your Subconscious Mind",
    author: "Joseph Murphy",
    size: 3100000,
    uploadedAt: Date.now() - 86400000 * 5,
    lastReadAt: Date.now() - 3600000 * 14,
    currentPage: 52,
    totalPages: 280,
    language: "English",
    fileType: 'sample',
    coverColor: 'color-F5ADCD',
    category: 'Best choice',
    favorite: true,
    planToRead: false,
    completed: false,
    rating: 5.0,
    contentData: `# The Treasure House Within You\n\nInfinite riches are all around you if you will open your mental eyes and behold the treasure house of infinity within you.\n\nThere is a gold mine within you from which you can extract everything you need to live life gloriously, joyously, and abundantly.`
  },
  {
    id: 'doc-3',
    name: "The Body Keeps the Score",
    title: "The Body Keeps the Score",
    author: "Bessel van der Kolk, M.D.",
    size: 4200000,
    uploadedAt: Date.now() - 86400000 * 2,
    lastReadAt: Date.now() - 3600000 * 5,
    currentPage: 88,
    totalPages: 464,
    language: "English",
    fileType: 'sample',
    coverColor: 'color-1856B7',
    category: 'Best choice',
    favorite: true,
    planToRead: false,
    completed: false,
    rating: 4.9,
    contentData: `# Part 1: The Rediscovery of Trauma\n\nBrain, mind, and body in the healing of trauma.\n\nTrauma is not just an event that took place somewhere in the past; it is also the footprint left by that experience on mind, brain, and body.`
  },
  {
    id: 'doc-4',
    name: "To The Lighthouse",
    title: "To The Lighthouse",
    author: "Virginia Woolf",
    size: 1890000,
    uploadedAt: Date.now() - 86400000 * 6,
    lastReadAt: Date.now() - 3600000 * 20,
    currentPage: 12,
    totalPages: 198,
    language: "English",
    fileType: 'sample',
    coverColor: 'color-E6DFD3',
    category: 'Best choice',
    favorite: false,
    planToRead: true,
    completed: false,
    rating: 4.8,
    contentData: `# Section 1: The Window\n\n"Yes, of course, if it's fine tomorrow," said Mrs. Ramsay. "But you'll have to be up with the lark," she added.\n\nTo the little boy sitting on the floor, her words conveyed extraordinary joy.`
  },
  {
    id: 'doc-5',
    name: "Normal People",
    title: "Normal People",
    author: "Sally Rooney",
    size: 2750000,
    uploadedAt: Date.now() - 86400000 * 8,
    lastReadAt: Date.now() - 86400000 * 1,
    currentPage: 260,
    totalPages: 260,
    language: "English",
    fileType: 'sample',
    coverColor: 'color-F3C623',
    category: 'Best choice',
    favorite: true,
    planToRead: false,
    completed: true,
    rating: 4.9,
    contentData: `# January 2011\n\nConnell comes out of the kitchen with a glass of water. Marianne is sitting on the sofa looking at her shoes.\n\nThey live in Carricklea, a small town in County Sligo.`
  },
  {
    id: 'doc-6',
    name: "Call Me by Your Name",
    title: "Call Me by Your Name",
    author: "André Aciman",
    size: 2890000,
    uploadedAt: Date.now() - 86400000 * 12,
    lastReadAt: Date.now() - 86400000 * 6,
    currentPage: 110,
    totalPages: 250,
    language: "English",
    fileType: 'sample',
    coverColor: 'color-1856B7',
    category: 'Romance',
    favorite: true,
    planToRead: false,
    completed: false,
    rating: 4.9,
    contentData: `# First Part: If Not Later, When?\n\n"Later!" The word, the voice, the attitude. I'd never heard anyone use "later" to say goodbye before.`
  },
  {
    id: 'doc-7',
    name: "The Little Prince (Le Petit Prince)",
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    size: 1450000,
    uploadedAt: Date.now() - 86400000 * 14,
    lastReadAt: Date.now() - 86400000 * 7,
    currentPage: 85,
    totalPages: 85,
    language: "French",
    fileType: 'sample',
    coverColor: 'color-530517',
    category: 'For Children',
    favorite: true,
    planToRead: false,
    completed: true,
    rating: 5.0,
    contentData: `# Chapitre I\n\nLorsque j'avais six ans j'ai vu, une fois, une magnifique image.\n\nOn ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.`
  },
  {
    id: 'doc-8',
    name: "Don't Go Crazy Without Me",
    title: "Don't Go Crazy Without Me",
    author: "Deborah Lott",
    size: 2450000,
    uploadedAt: Date.now() - 86400000 * 15,
    lastReadAt: Date.now() - 86400000 * 10,
    currentPage: 1,
    totalPages: 240,
    language: "English",
    fileType: 'sample',
    coverColor: 'color-1E1D22',
    category: 'Best choice',
    favorite: false,
    planToRead: true,
    completed: false,
    rating: 4.6,
    contentData: `# Chapter 1: The Arrival\n\nIt was a quiet afternoon when the letters arrived. Deborah sat on the veranda, watching the shadows lengthen across the oak-lined path.`
  },
  {
    id: 'doc-9',
    name: "Brilliant Ideas & Notes",
    title: "Brilliant Ideas & Notes",
    author: "Lingoflow Studio",
    size: 1800000,
    uploadedAt: Date.now() - 86400000 * 1,
    lastReadAt: Date.now() - 3600000 * 1,
    currentPage: 18,
    totalPages: 120,
    language: "English",
    fileType: 'sample',
    coverColor: 'color-E6DFD3',
    category: 'Best choice',
    favorite: true,
    planToRead: false,
    completed: false,
    rating: 4.9,
    contentData: `# Brilliant Ideas\n\nCollection of creative thoughts, vocabulary notes, and linguistic explorations.`
  },
  {
    id: 'doc-10',
    name: "Mata Yang Enak Dipandang",
    title: "Mata Yang Enak Dipandang",
    author: "Ahmad Tohari",
    size: 2100000,
    uploadedAt: Date.now() - 86400000 * 4,
    lastReadAt: Date.now() - 3600000 * 8,
    currentPage: 45,
    totalPages: 180,
    language: "Indonesian",
    fileType: 'sample',
    coverColor: 'color-[#9EBC67]',
    category: 'Best choice',
    favorite: true,
    planToRead: false,
    completed: false,
    rating: 5.0,
    contentData: `# Kumpulan Cerita Pendek\n\nKisah-kisah kehidupan pedesaan dan panorama alam yang menyentuh hati.`
  }
];

export const INITIAL_FOLDERS: Folder[] = [];

export const INITIAL_DECKS: Deck[] = [];

export const INITIAL_VOCABULARY: VocabularyItem[] = [];

